Available help:
  ABORT                            DEALLOCATE
  ALTER AGGREGATE                  DECLARE
  ALTER COLLATION                  DELETE
  ALTER CONVERSION                 DISCARD
  ALTER DATABASE                   DO
  ALTER DEFAULT PRIVILEGES         DROP AGGREGATE
  ALTER DOMAIN                     DROP CAST
  ALTER EVENT TRIGGER              DROP COLLATION
  ALTER EXTENSION                  DROP CONVERSION
  ALTER FOREIGN DATA WRAPPER       DROP DATABASE
  ALTER FOREIGN TABLE              DROP DOMAIN
  ALTER FUNCTION                   DROP EVENT TRIGGER
  ALTER GROUP                      DROP EXTENSION
  ALTER INDEX                      DROP FOREIGN DATA WRAPPER
  ALTER LANGUAGE                   DROP FOREIGN TABLE
  ALTER LARGE OBJECT               DROP FUNCTION
  ALTER MATERIALIZED VIEW          DROP GROUP
  ALTER OPERATOR                   DROP INDEX
  ALTER OPERATOR CLASS             DROP LANGUAGE
  ALTER OPERATOR FAMILY            DROP MATERIALIZED VIEW
  ALTER ROLE                       DROP OPERATOR
  ALTER RULE                       DROP OPERATOR CLASS
  ALTER SCHEMA                     DROP OPERATOR FAMILY
  ALTER SEQUENCE                   DROP OWNED
  ALTER SERVER                     DROP ROLE
  ALTER TABLE                      DROP RULE
  ALTER TABLESPACE                 DROP SCHEMA
  ALTER TEXT SEARCH CONFIGURATION  DROP SEQUENCE
  ALTER TEXT SEARCH DICTIONARY     DROP SERVER
  ALTER TEXT SEARCH PARSER         DROP TABLE
  ALTER TEXT SEARCH TEMPLATE       DROP TABLESPACE
  ALTER TRIGGER                    DROP TEXT SEARCH CONFIGURATION
  ALTER TYPE                       DROP TEXT SEARCH DICTIONARY
  ALTER USER                       DROP TEXT SEARCH PARSER
  ALTER USER MAPPING               DROP TEXT SEARCH TEMPLATE
  ALTER VIEW                       DROP TRIGGER
  ANALYZE                          DROP TYPE
  BEGIN                            DROP USER
  CHECKPOINT                       DROP USER MAPPING
  CLOSE                            DROP VIEW
  CLUSTER                          END
  COMMENT                          EXECUTE
  COMMIT                           EXPLAIN
  COMMIT PREPARED                  FETCH
  COPY                             GRANT
  CREATE AGGREGATE                 INSERT
  CREATE CAST                      LISTEN
  CREATE COLLATION                 LOAD
  CREATE CONVERSION                LOCK
  CREATE DATABASE                  MOVE
  CREATE DOMAIN                    NOTIFY
  CREATE EVENT TRIGGER             PREPARE
  CREATE EXTENSION                 PREPARE TRANSACTION
  CREATE FOREIGN DATA WRAPPER      REASSIGN OWNED
  CREATE FOREIGN TABLE             REFRESH MATERIALIZED VIEW
  CREATE FUNCTION                  REINDEX
  CREATE GROUP                     RELEASE SAVEPOINT
  CREATE INDEX                     RESET
  CREATE LANGUAGE                  REVOKE
  CREATE MATERIALIZED VIEW         ROLLBACK
  CREATE OPERATOR                  ROLLBACK PREPARED
  CREATE OPERATOR CLASS            ROLLBACK TO SAVEPOINT
  CREATE OPERATOR FAMILY           SAVEPOINT
  CREATE ROLE                      SECURITY LABEL
  CREATE RULE                      SELECT
  CREATE SCHEMA                    SELECT INTO
  CREATE SEQUENCE                  SET
  CREATE SERVER                    SET CONSTRAINTS
  CREATE TABLE                     SET ROLE
  CREATE TABLE AS                  SET SESSION AUTHORIZATION
  CREATE TABLESPACE                SET TRANSACTION
  CREATE TEXT SEARCH CONFIGURATION SHOW
  CREATE TEXT SEARCH DICTIONARY    START TRANSACTION
  CREATE TEXT SEARCH PARSER        TABLE
  CREATE TEXT SEARCH TEMPLATE      TRUNCATE
  CREATE TRIGGER                   UNLISTEN
  CREATE TYPE                      UPDATE
  CREATE USER                      VACUUM
  CREATE USER MAPPING              VALUES
  CREATE VIEW                      WITH
